spring:
  datasource:
    url: "jdbc:postgresql://db-container-name:5432/template-db"
    username: "postgres"
    password: "password"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update